# Generated by Django 4.1 on 2022-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=100, verbose_name='Product Name')),
                ('proDesc', models.TextField(verbose_name='Product Description')),
                ('proPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price')),
                ('proCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost')),
                ('proCreated', models.DateTimeField(verbose_name='Product Created')),
            ],
        ),
    ]
