# Generated by Django 4.1 on 2022-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='proImage',
            field=models.ImageField(upload_to='ProductImg/', verbose_name='Image'),
        ),
    ]
