# Generated by Django 4.1 on 2022-08-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimg_proimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatMain', models.CharField(max_length=50)),
                ('CatDesc', models.TextField()),
                ('CatImg', models.ImageField(upload_to='category/')),
                ('CatParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
