# Generated by Django 4.1 on 2022-08-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proCost',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proPrice',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCalternative', models.ManyToManyField(related_name='Accessories_products', to='product.product')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainACC_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Product_Accessory',
                'verbose_name_plural': 'Product_Accessories',
            },
        ),
    ]
