# Generated by Django 4.1 on 2022-08-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_procost_alter_product_proprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatImg',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatMain',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CatParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main_category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCalternative',
            field=models.ManyToManyField(related_name='Accessories_products', to='product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainACC_product', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALalternative',
            field=models.ManyToManyField(related_name='Alternative_products', to='product.product', verbose_name='Alternative'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='product'),
        ),
    ]
