# Generated by Django 4.1 on 2022-08-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_proimg_alter_product_procategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Product Discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proslug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='proCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price'),
        ),
    ]
