# Generated by Django 4.1 on 2022-08-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0012_product_prodiscount_product_proslug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name=' category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proCreated',
            field=models.DateTimeField(verbose_name=' Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proDesc',
            field=models.TextField(verbose_name=' Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proDiscount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=' Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name=' Iamge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='probrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name=' brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proslug',
            field=models.SlugField(blank=True, null=True, verbose_name=' slug'),
        ),
    ]
